import { AccessibilityLocation } from './types';

export const sampleLocations: AccessibilityLocation[] = [
  // ─── 서울 ───────────────────────────────────────────────
  {
    id: 'seoul-station',
    name: '서울역',
    type: 'subway',
    lat: 37.5547,
    lng: 126.9707,
    address: '서울특별시 용산구 한강대로 405',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F', note: '1·4호선, KTX 모든 층 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '승차권 발매기 음성 안내 지원' },
      steps: { hasSteps: false, ramp: true, note: '주 출입구 경사로 완비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-10',
    source: 'official',
  },
  {
    id: 'gangnam-station',
    name: '강남역',
    type: 'subway',
    lat: 37.4979,
    lng: 127.0276,
    address: '서울특별시 강남구 강남대로 396',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F', note: '2호선 상·하행 모두 엘리베이터 이용 가능' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false, note: '일부 발매기만 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'hongik-station',
    name: '홍대입구역',
    type: 'subway',
    lat: 37.5572,
    lng: 126.9245,
    address: '서울특별시 마포구 양화로 160',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: false, note: '음성 안내 미지원, 터치스크린만 가능' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'gwanghwamun-square',
    name: '광화문광장',
    type: 'public',
    lat: 37.5752,
    lng: 126.9769,
    address: '서울특별시 종로구 세종대로 172',
    accessibility: {
      elevator: { available: false, note: '지하 공간 없음' },
      kiosk: { available: true, voiceSupport: false, note: '안내 키오스크 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 3, ramp: true, note: '광장 진입 단차 3cm 이하, 경사로 있음' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'user',
  },
  {
    id: 'severance-hospital',
    name: '세브란스병원',
    type: 'hospital',
    lat: 37.5622,
    lng: 126.9405,
    address: '서울특별시 서대문구 연세로 50-1',
    accessibility: {
      elevator: { available: true, floors: 'B5~지상 21F', note: '본관·별관 모든 층 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '원무 접수 키오스크 음성·대형글씨 완비' },
      steps: { hasSteps: false, ramp: true, note: '주출입구 자동문·경사로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'coex-mall',
    name: 'COEX 몰',
    type: 'shopping',
    lat: 37.5113,
    lng: 127.0592,
    address: '서울특별시 강남구 영동대로 513',
    accessibility: {
      elevator: { available: true, floors: 'B3~5F' },
      kiosk: { available: true, voiceSupport: false, note: '안내 키오스크 음성 미지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'user',
  },
  {
    id: 'gyeongbokgung',
    name: '경복궁',
    type: 'cultural',
    lat: 37.5796,
    lng: 126.9770,
    address: '서울특별시 종로구 사직로 161',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false, note: '입장권 발매 키오스크, 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 15, ramp: false, note: '정문(흥례문) 계단 단차 약 15cm, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '일부 구역만 접근 가능, 사전 문의 권장' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-20',
    source: 'user',
  },
  {
    id: 'itaewon-station',
    name: '이태원역',
    type: 'subway',
    lat: 37.5345,
    lng: 126.9943,
    address: '서울특별시 용산구 이태원로 177',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-01',
    source: 'osm',
  },
  {
    id: 'lotte-world-tower',
    name: '롯데월드타워',
    type: 'building',
    lat: 37.5126,
    lng: 127.1026,
    address: '서울특별시 송파구 올림픽로 300',
    accessibility: {
      elevator: { available: true, floors: 'B7~123F', note: '고속 엘리베이터 및 장애인용 별도 엘리베이터 운영' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-15',
    source: 'official',
  },
  {
    id: 'insadong',
    name: '인사동 쌈지길',
    type: 'shopping',
    lat: 37.5742,
    lng: 126.9855,
    address: '서울특별시 종로구 인사동길 44',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F', note: '나선형 통로 외 엘리베이터 별도 운영' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 8, ramp: true, note: '일부 샵 입구 단차 최대 8cm' },
      wheelchair: { accessible: 'limited', note: '엘리베이터 이용 시 대부분 층 접근 가능' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-10',
    source: 'user',
  },
  {
    id: 'national-museum',
    name: '국립중앙박물관',
    type: 'cultural',
    lat: 37.5240,
    lng: 126.9799,
    address: '서울특별시 용산구 서빙고로 137',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '안내·티켓 키오스크 완전 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'sinchon-station',
    name: '신촌역',
    type: 'subway',
    lat: 37.5551,
    lng: 126.9368,
    address: '서울특별시 서대문구 신촌로 83',
    accessibility: {
      elevator: { available: false, note: '엘리베이터 미설치, 에스컬레이터만 운영' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '출구 계단 단차 약 20cm, 경사로 없음' },
      wheelchair: { accessible: 'no', note: '휠체어 이용 매우 어려움, 인근 홍대입구역 이용 권장' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-08-05',
    source: 'user',
  },
  {
    id: 'dongdaemun-dps',
    name: '동대문디자인플라자(DDP)',
    type: 'cultural',
    lat: 37.5669,
    lng: 127.0095,
    address: '서울특별시 중구 을지로 281',
    accessibility: {
      elevator: { available: true, floors: 'B3~4F', note: '전 층 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'official',
  },
  {
    id: 'seoul-arts-center',
    name: '예술의전당',
    type: 'cultural',
    lat: 37.4773,
    lng: 127.0144,
    address: '서울특별시 서초구 남부순환로 2406',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: true, voiceSupport: false, note: '티켓 발권 키오스크, 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'seoul-asan-hospital',
    name: '서울아산병원',
    type: 'hospital',
    lat: 37.5270,
    lng: 127.1083,
    address: '서울특별시 송파구 올림픽로43길 88',
    accessibility: {
      elevator: { available: true, floors: 'B5~28F', note: '각 동 별도 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },

  // ─── 강남 ───────────────────────────────────────────────
  {
    id: 'gangnam-gu-office',
    name: '강남구청',
    type: 'building',
    lat: 37.5172,
    lng: 127.0473,
    address: '서울특별시 강남구 학동로 426',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '민원 발급 키오스크 완전 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'samsung-station',
    name: '삼성역',
    type: 'subway',
    lat: 37.5088,
    lng: 127.0631,
    address: '서울특별시 강남구 테헤란로 213',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'yeoksam-station',
    name: '역삼역',
    type: 'subway',
    lat: 37.5007,
    lng: 127.0362,
    address: '서울특별시 강남구 강남대로 316',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'seonleung-station',
    name: '선릉역',
    type: 'subway',
    lat: 37.5047,
    lng: 127.0491,
    address: '서울특별시 강남구 테헤란로 411',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'apgujeong-rodeo',
    name: '압구정로데오역',
    type: 'subway',
    lat: 37.5274,
    lng: 127.0399,
    address: '서울특별시 강남구 선릉로 720',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'user',
  },
  {
    id: 'starfield-coex',
    name: '스타필드 코엑스몰',
    type: 'shopping',
    lat: 37.5125,
    lng: 127.0591,
    address: '서울특별시 강남구 봉은사로 524',
    accessibility: {
      elevator: { available: true, floors: 'B3~6F', note: '각 구역별 엘리베이터 설치' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여 서비스' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-10',
    source: 'official',
  },
  {
    id: 'gangnam-severance',
    name: '강남세브란스병원',
    type: 'hospital',
    lat: 37.4924,
    lng: 127.0783,
    address: '서울특별시 강남구 언주로 211',
    accessibility: {
      elevator: { available: true, floors: 'B5~20F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },
  {
    id: 'samsung-medical-center',
    name: '삼성서울병원',
    type: 'hospital',
    lat: 37.4885,
    lng: 127.0853,
    address: '서울특별시 강남구 일원로 81',
    accessibility: {
      elevator: { available: true, floors: 'B5~22F', note: '본관·별관·암센터 전 층 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-12',
    source: 'official',
  },
  {
    id: 'gangnam-cgv',
    name: 'CGV 강남',
    type: 'cultural',
    lat: 37.4970,
    lng: 127.0276,
    address: '서울특별시 강남구 강남대로 438',
    accessibility: {
      elevator: { available: true, floors: '1F~9F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '발권 키오스크 음성·대형글씨 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 좌석 사전 예약 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'hyundai-motors-studio-gangnam',
    name: '현대모터스튜디오 서울',
    type: 'cultural',
    lat: 37.5068,
    lng: 127.0559,
    address: '서울특별시 강남구 테헤란로 517',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'gangnam-lotte-cinema',
    name: '롯데시네마 강남',
    type: 'cultural',
    lat: 37.5002,
    lng: 127.0267,
    address: '서울특별시 강남구 강남대로 542',
    accessibility: {
      elevator: { available: true, floors: '1F~8F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'user',
  },
  {
    id: 'gangnam-post-office',
    name: '강남우체국',
    type: 'building',
    lat: 37.5009,
    lng: 127.0254,
    address: '서울특별시 강남구 강남대로 622',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-20',
    source: 'user',
  },
  {
    id: 'gangnam-tax-office',
    name: '강남세무서',
    type: 'building',
    lat: 37.5089,
    lng: 127.0407,
    address: '서울특별시 강남구 논현로 430',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },
  {
    id: 'sinnonhyeon-station',
    name: '신논현역',
    type: 'subway',
    lat: 37.5047,
    lng: 127.0250,
    address: '서울특별시 강남구 강남대로 지하 566',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'gu-banhapdan',
    name: '학동역',
    type: 'subway',
    lat: 37.5165,
    lng: 127.0388,
    address: '서울특별시 강남구 논현로 430',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-15',
    source: 'osm',
  },
  {
    id: 'daechi-station',
    name: '대치역',
    type: 'subway',
    lat: 37.4944,
    lng: 127.0607,
    address: '서울특별시 강남구 남부순환로 2933',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-05',
    source: 'osm',
  },
  {
    id: 'gangnam-gu-library',
    name: '강남구립도서관',
    type: 'cultural',
    lat: 37.5085,
    lng: 127.0557,
    address: '서울특별시 강남구 삼성로 212',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-18',
    source: 'user',
  },
  {
    id: 'bongeunsa',
    name: '봉은사',
    type: 'cultural',
    lat: 37.5148,
    lng: 127.0589,
    address: '서울특별시 강남구 봉은사로 531',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true, note: '경내 일부 경사로 정비' },
      wheelchair: { accessible: 'limited', note: '중심 법당 접근 가능, 외곽 전각 어려움' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-25',
    source: 'user',
  },

  // ─── 용산 ───────────────────────────────────────────────
  {
    id: 'yongsan-station',
    name: '용산역',
    type: 'subway',
    lat: 37.5298,
    lng: 126.9649,
    address: '서울특별시 용산구 한강대로 23길 55',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 3F', note: 'KTX·경의중앙선·1호선 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-08',
    source: 'official',
  },
  {
    id: 'ipark-mall',
    name: '아이파크몰 용산',
    type: 'shopping',
    lat: 37.5296,
    lng: 126.9643,
    address: '서울특별시 용산구 한강대로 23길 55',
    accessibility: {
      elevator: { available: true, floors: 'B4~9F', note: '각 구역 엘리베이터 다수 설치' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-30',
    source: 'official',
  },
  {
    id: 'national-museum-of-korea',
    name: '국립한글박물관',
    type: 'cultural',
    lat: 37.5243,
    lng: 126.9800,
    address: '서울특별시 용산구 서빙고로 139',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-14',
    source: 'official',
  },
  {
    id: 'war-memorial-korea',
    name: '전쟁기념관',
    type: 'cultural',
    lat: 37.5362,
    lng: 126.9771,
    address: '서울특별시 용산구 이태원로 29',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },
  {
    id: 'yongsan-electronics-market',
    name: '용산전자상가',
    type: 'shopping',
    lat: 37.5323,
    lng: 126.9697,
    address: '서울특별시 용산구 청파로 74',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F', note: '나진·선인·전자랜드 각 건물 엘리베이터 운행' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: false, note: '건물 간 연결 통로 단차 있음' },
      wheelchair: { accessible: 'limited', note: '건물 내부 엘리베이터 이용 시 접근 가능' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-08-20',
    source: 'user',
  },
  {
    id: 'namsan-cable-car',
    name: '남산케이블카',
    type: 'public',
    lat: 37.5513,
    lng: 126.9800,
    address: '서울특별시 중구 소파로 83',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 15, ramp: false, note: '탑승장 계단, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '케이블카 탑승 가능하나 접근로 계단 있음' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-05',
    source: 'user',
  },
  {
    id: 'namsan-n-tower',
    name: 'N서울타워',
    type: 'building',
    lat: 37.5512,
    lng: 126.9882,
    address: '서울특별시 용산구 남산공원길 105',
    accessibility: {
      elevator: { available: true, floors: '1F~5F', note: '전망대 전용 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-12',
    source: 'official',
  },
  {
    id: 'haebangchon-hospital',
    name: '순천향대학교 서울병원',
    type: 'hospital',
    lat: 37.5393,
    lng: 126.9679,
    address: '서울특별시 용산구 대사관로 59',
    accessibility: {
      elevator: { available: true, floors: 'B3~12F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'ichon-station',
    name: '이촌역',
    type: 'subway',
    lat: 37.5225,
    lng: 126.9716,
    address: '서울특별시 용산구 이촌로 72',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-25',
    source: 'osm',
  },
  {
    id: 'yongsan-family-park',
    name: '용산가족공원',
    type: 'public',
    lat: 37.5242,
    lng: 126.9773,
    address: '서울특별시 용산구 서빙고로 185',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 전체 평탄한 산책로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-30',
    source: 'user',
  },
  {
    id: 'hangangjin-station',
    name: '한강진역',
    type: 'subway',
    lat: 37.5391,
    lng: 126.9884,
    address: '서울특별시 용산구 이태원로 257',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-02',
    source: 'osm',
  },
  {
    id: 'itaewon-global-village-center',
    name: '이태원 글로벌빌리지센터',
    type: 'public',
    lat: 37.5340,
    lng: 126.9940,
    address: '서울특별시 용산구 이태원로 177',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 8, ramp: true },
      wheelchair: { accessible: 'limited' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-15',
    source: 'user',
  },

  // ─── 홍대 · 마포 ─────────────────────────────────────
  {
    id: 'hapjeong-station',
    name: '합정역',
    type: 'subway',
    lat: 37.5498,
    lng: 126.9147,
    address: '서울특별시 마포구 양화로 93',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'sangsu-station',
    name: '상수역',
    type: 'subway',
    lat: 37.5481,
    lng: 126.9231,
    address: '서울특별시 마포구 와우산로 98',
    accessibility: {
      elevator: { available: false, note: '엘리베이터 미설치' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false },
      wheelchair: { accessible: 'no', note: '인근 합정역 이용 권장' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-12',
    source: 'user',
  },
  {
    id: 'mapo-gu-office',
    name: '마포구청',
    type: 'building',
    lat: 37.5581,
    lng: 126.9087,
    address: '서울특별시 마포구 월드컵로 212',
    accessibility: {
      elevator: { available: true, floors: 'B1~9F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-20',
    source: 'official',
  },
  {
    id: 'seoulworld-cup-stadium',
    name: '서울월드컵경기장',
    type: 'public',
    lat: 37.5683,
    lng: 126.8973,
    address: '서울특별시 마포구 월드컵로 240',
    accessibility: {
      elevator: { available: true, floors: '1F~5F', note: '주 게이트별 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 관람석 별도 구역' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-10',
    source: 'official',
  },
  {
    id: 'hongik-univ-station-2',
    name: '홍대입구역 2호선',
    type: 'subway',
    lat: 37.5573,
    lng: 126.9246,
    address: '서울특별시 마포구 양화로 160',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-25',
    source: 'official',
  },
  {
    id: 'aha-park-hongdae',
    name: '홍대 놀이터(AHA Park)',
    type: 'public',
    lat: 37.5534,
    lng: 126.9237,
    address: '서울특별시 마포구 와우산로21길',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: false, accessible: false },
    },
    lastUpdated: '2024-07-01',
    source: 'user',
  },
  {
    id: 'mapo-culture-foundation',
    name: '마포문화재단 마포아트센터',
    type: 'cultural',
    lat: 37.5588,
    lng: 126.9115,
    address: '서울특별시 마포구 월드컵로 279',
    accessibility: {
      elevator: { available: true, floors: 'B2~5F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },
  {
    id: 'mapo-samsung-hospital',
    name: '이화여자대학교 서울병원',
    type: 'hospital',
    lat: 37.5563,
    lng: 126.9444,
    address: '서울특별시 마포구 도화길 41',
    accessibility: {
      elevator: { available: true, floors: 'B3~12F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },
  {
    id: 'mangwon-market',
    name: '망원시장',
    type: 'shopping',
    lat: 37.5552,
    lng: 126.9052,
    address: '서울특별시 마포구 포은로8길 18',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: false, note: '시장 골목 미세 단차 다수' },
      wheelchair: { accessible: 'limited', note: '메인 통로는 이동 가능, 좁은 골목 어려움' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-20',
    source: 'user',
  },
  {
    id: 'cgv-hongdae',
    name: 'CGV 홍대',
    type: 'cultural',
    lat: 37.5561,
    lng: 126.9230,
    address: '서울특별시 마포구 양화로 188',
    accessibility: {
      elevator: { available: true, floors: '1F~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'hongdae-playground-park',
    name: '홍대 걷고싶은거리',
    type: 'public',
    lat: 37.5544,
    lng: 126.9226,
    address: '서울특별시 마포구 어울마당로',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '보행자 전용도로 평탄 정비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-12',
    source: 'user',
  },

  // ─── 건대 · 광진 ─────────────────────────────────────
  {
    id: 'konkuk-univ-station',
    name: '건대입구역',
    type: 'subway',
    lat: 37.5403,
    lng: 127.0700,
    address: '서울특별시 광진구 능동로 248',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },
  {
    id: 'konkuk-university-hospital',
    name: '건국대학교병원',
    type: 'hospital',
    lat: 37.5378,
    lng: 127.0758,
    address: '서울특별시 광진구 능동로 120-1',
    accessibility: {
      elevator: { available: true, floors: 'B4~16F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },
  {
    id: 'lotte-world-adventure',
    name: '롯데월드 어드벤처',
    type: 'public',
    lat: 37.5111,
    lng: 127.0983,
    address: '서울특별시 송파구 올림픽로 240',
    accessibility: {
      elevator: { available: true, floors: 'B2~4F', note: '실내 어드벤처 전 층 연결' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 입장 게이트 운영, 일부 탑승 제한 있음' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-28',
    source: 'official',
  },
  {
    id: 'guui-station',
    name: '구의역',
    type: 'subway',
    lat: 37.5445,
    lng: 127.0944,
    address: '서울특별시 광진구 자양로 185',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'osm',
  },
  {
    id: 'seungbu-shopping-mall',
    name: '스타시티몰',
    type: 'shopping',
    lat: 37.5395,
    lng: 127.0697,
    address: '서울특별시 광진구 능동로 90',
    accessibility: {
      elevator: { available: true, floors: 'B5~8F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'user',
  },
  {
    id: 'gwangjin-gu-office',
    name: '광진구청',
    type: 'building',
    lat: 37.5385,
    lng: 127.0822,
    address: '서울특별시 광진구 자양로 117',
    accessibility: {
      elevator: { available: true, floors: 'B1~6F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'children-grand-park',
    name: '어린이대공원',
    type: 'public',
    lat: 37.5486,
    lng: 127.0810,
    address: '서울특별시 광진구 능동로 216',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 내 주요 동선 경사로 완비' },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'official',
  },
  {
    id: 'ttukseom-hangang-park',
    name: '뚝섬한강공원',
    type: 'public',
    lat: 37.5290,
    lng: 127.0670,
    address: '서울특별시 광진구 강변북로 139',
    accessibility: {
      elevator: { available: true, floors: '1F~3F', note: '접근 육교 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-05',
    source: 'user',
  },
  {
    id: 'jayang-station',
    name: '자양역(5호선)',
    type: 'subway',
    lat: 37.5428,
    lng: 127.0942,
    address: '서울특별시 광진구 자양로 260',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-22',
    source: 'osm',
  },

  // ─── 신촌 · 은평 · 서대문 ───────────────────────────
  {
    id: 'ewha-campus',
    name: '이화여자대학교 ECC',
    type: 'cultural',
    lat: 37.5626,
    lng: 126.9469,
    address: '서울특별시 서대문구 이화여대길 52',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'seodaemun-independent-hall',
    name: '서대문독립공원(형무소역사관)',
    type: 'cultural',
    lat: 37.5720,
    lng: 126.9590,
    address: '서울특별시 서대문구 통일로 251',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true },
      wheelchair: { accessible: 'limited', note: '역사관 건물 내부 계단 많음, 일부 우회 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-28',
    source: 'user',
  },
  {
    id: 'sinchon-yonsei-hospital',
    name: '신촌 세브란스병원',
    type: 'hospital',
    lat: 37.5622,
    lng: 126.9405,
    address: '서울특별시 서대문구 연세로 50-1',
    accessibility: {
      elevator: { available: true, floors: 'B5~21F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'seodaemun-natural-history',
    name: '서대문자연사박물관',
    type: 'cultural',
    lat: 37.5783,
    lng: 126.9355,
    address: '서울특별시 서대문구 연희로32길 51',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-20',
    source: 'official',
  },

  // ─── 성수 · 왕십리 ──────────────────────────────────
  {
    id: 'seongsu-station',
    name: '성수역',
    type: 'subway',
    lat: 37.5447,
    lng: 127.0560,
    address: '서울특별시 성동구 뚝섬로 425',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-03',
    source: 'official',
  },
  {
    id: 'wangsimni-station',
    name: '왕십리역',
    type: 'subway',
    lat: 37.5614,
    lng: 127.0375,
    address: '서울특별시 성동구 왕십리광장로 17',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 2F', note: '2호선·5호선·경의중앙선 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },
  {
    id: 'sungdong-gu-office',
    name: '성동구청',
    type: 'building',
    lat: 37.5635,
    lng: 127.0367,
    address: '서울특별시 성동구 고산자로 270',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'seoul-forest',
    name: '서울숲',
    type: 'public',
    lat: 37.5443,
    lng: 127.0374,
    address: '서울특별시 성동구 뚝섬로 273',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '주요 산책로 평탄 정비' },
      wheelchair: { accessible: 'yes', note: '휠체어 대여 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },

  // ─── 신림 · 관악 ─────────────────────────────────────
  {
    id: 'sillim-station',
    name: '신림역',
    type: 'subway',
    lat: 37.4844,
    lng: 126.9294,
    address: '서울특별시 관악구 신림로 249',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'official',
  },
  {
    id: 'gwanak-gu-office',
    name: '관악구청',
    type: 'building',
    lat: 37.4776,
    lng: 126.9516,
    address: '서울특별시 관악구 관악로 145',
    accessibility: {
      elevator: { available: true, floors: 'B1~6F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },

  // ─── 노원 · 도봉 ─────────────────────────────────────
  {
    id: 'nowon-station',
    name: '노원역',
    type: 'subway',
    lat: 37.6554,
    lng: 127.0562,
    address: '서울특별시 노원구 동일로 1414',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F', note: '4호선·7호선 환승 가능' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'nowon-gu-office',
    name: '노원구청',
    type: 'building',
    lat: 37.6544,
    lng: 127.0563,
    address: '서울특별시 노원구 노해로 437',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },
  {
    id: 'junggye-station',
    name: '중계역',
    type: 'subway',
    lat: 37.6350,
    lng: 127.0680,
    address: '서울특별시 노원구 동일로 1430',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-18',
    source: 'osm',
  },

  // ─── 종로 · 중구 ─────────────────────────────────────
  {
    id: 'jonggak-station',
    name: '종각역',
    type: 'subway',
    lat: 37.5702,
    lng: 126.9822,
    address: '서울특별시 종로구 종로 지하31',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },
  {
    id: 'jongno3ga-station',
    name: '종로3가역',
    type: 'subway',
    lat: 37.5706,
    lng: 126.9918,
    address: '서울특별시 종로구 종로 지하130',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F', note: '1호선·3호선·5호선 연결 엘리베이터' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'cheonggyecheon-stream',
    name: '청계천',
    type: 'public',
    lat: 37.5695,
    lng: 126.9795,
    address: '서울특별시 종로구 청계천로 1',
    accessibility: {
      elevator: { available: true, floors: '지상~하부 산책로', note: '주요 접근 지점 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true, note: '하천 접근 계단, 주요 구간 경사로 병행' },
      wheelchair: { accessible: 'yes', note: '하부 산책로 전체 평탄' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'myeongdong-station',
    name: '명동역',
    type: 'subway',
    lat: 37.5634,
    lng: 126.9862,
    address: '서울특별시 중구 명동길 지하14',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-28',
    source: 'official',
  },
  {
    id: 'lotte-department-myeongdong',
    name: '롯데백화점 명동본점',
    type: 'shopping',
    lat: 37.5652,
    lng: 126.9823,
    address: '서울특별시 중구 남대문로 81',
    accessibility: {
      elevator: { available: true, floors: 'B6~12F', note: '에비뉴엘 포함 전 동 엘리베이터' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여 서비스' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-02',
    source: 'official',
  },
  {
    id: 'shinsegae-myeongdong',
    name: '신세계백화점 본점',
    type: 'shopping',
    lat: 37.5603,
    lng: 126.9774,
    address: '서울특별시 중구 소공로 63',
    accessibility: {
      elevator: { available: true, floors: 'B3~8F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },
  {
    id: 'seoul-city-hall',
    name: '서울시청',
    type: 'building',
    lat: 37.5662,
    lng: 126.9779,
    address: '서울특별시 중구 세종대로 110',
    accessibility: {
      elevator: { available: true, floors: 'B3~13F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-30',
    source: 'official',
  },
  {
    id: 'deoksugung',
    name: '덕수궁',
    type: 'cultural',
    lat: 37.5659,
    lng: 126.9751,
    address: '서울특별시 중구 세종대로 99',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true, note: '정문 경사로 설치, 내부 일부 비포장' },
      wheelchair: { accessible: 'limited', note: '정원 및 석조전 주변 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-28',
    source: 'user',
  },

  // ─── 잠실 · 송파 ─────────────────────────────────────
  {
    id: 'jamsil-station',
    name: '잠실역',
    type: 'subway',
    lat: 37.5133,
    lng: 127.1002,
    address: '서울특별시 송파구 올림픽로 지하265',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F', note: '2호선·8호선 환승 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-28',
    source: 'official',
  },
  {
    id: 'olympic-park',
    name: '올림픽공원',
    type: 'public',
    lat: 37.5207,
    lng: 127.1219,
    address: '서울특별시 송파구 올림픽로 424',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 내 주요 도로 평탄, 경사로 완비' },
      wheelchair: { accessible: 'yes', note: '휠체어 대여 서비스 운영' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-22',
    source: 'official',
  },
  {
    id: 'lotte-world-mall',
    name: '롯데월드몰',
    type: 'shopping',
    lat: 37.5125,
    lng: 127.1007,
    address: '서울특별시 송파구 올림픽로 300',
    accessibility: {
      elevator: { available: true, floors: 'B6~9F', note: '전 구역 다수 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-12',
    source: 'official',
  },

  // ─── 여의도 ──────────────────────────────────────────
  {
    id: 'yeouido-station',
    name: '여의도역',
    type: 'subway',
    lat: 37.5216,
    lng: 126.9247,
    address: '서울특별시 영등포구 여의나루로 지하53',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'ifc-mall',
    name: 'IFC몰',
    type: 'shopping',
    lat: 37.5254,
    lng: 126.9267,
    address: '서울특별시 영등포구 국제금융로 10',
    accessibility: {
      elevator: { available: true, floors: 'B3~5F', note: '여의도역 직결 엘리베이터' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-08',
    source: 'official',
  },
  {
    id: 'yeouido-hangang-park',
    name: '여의도한강공원',
    type: 'public',
    lat: 37.5284,
    lng: 126.9323,
    address: '서울특별시 영등포구 여의동로 330',
    accessibility: {
      elevator: { available: true, floors: '지상~지하 연결', note: '지하차도 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'national-assembly',
    name: '국회의사당',
    type: 'building',
    lat: 37.5322,
    lng: 126.9147,
    address: '서울특별시 영등포구 의사당대로 1',
    accessibility: {
      elevator: { available: true, floors: 'B2~6F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },

  // ─── 영등포 · 구로 ─────────────────────────────────
  {
    id: 'yeongdeungpo-station',
    name: '영등포역',
    type: 'subway',
    lat: 37.5158,
    lng: 126.9072,
    address: '서울특별시 영등포구 경인로 846',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },
  {
    id: 'times-square',
    name: '타임스퀘어',
    type: 'shopping',
    lat: 37.5172,
    lng: 126.9032,
    address: '서울특별시 영등포구 영중로 15',
    accessibility: {
      elevator: { available: true, floors: 'B4~9F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },

  // ─── 부산 ───────────────────────────────────────────────
  {
    id: 'busan-station',
    name: '부산역',
    type: 'subway',
    lat: 35.1145,
    lng: 129.0420,
    address: '부산광역시 동구 중앙대로 206',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F', note: 'KTX·무궁화 연결 전 층' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-10',
    source: 'official',
  },
  {
    id: 'haeundae-beach',
    name: '해운대해수욕장',
    type: 'public',
    lat: 35.1588,
    lng: 129.1603,
    address: '부산광역시 해운대구 해운대해변로 264',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '해변 진입 경사로 완비' },
      wheelchair: { accessible: 'yes', note: '해변 전용 휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-15',
    source: 'user',
  },
  {
    id: 'busan-cinema-center',
    name: '영화의전당',
    type: 'cultural',
    lat: 35.1598,
    lng: 129.1221,
    address: '부산광역시 해운대구 수영강변대로 120',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'busan-national-museum',
    name: '국립부산박물관',
    type: 'cultural',
    lat: 35.1070,
    lng: 129.0896,
    address: '부산광역시 남구 유엔평화로 63',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-30',
    source: 'official',
  },
  {
    id: 'busan-university-hospital',
    name: '부산대학교병원',
    type: 'hospital',
    lat: 35.1262,
    lng: 129.0219,
    address: '부산광역시 서구 구덕로 179',
    accessibility: {
      elevator: { available: true, floors: 'B2~15F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },
  {
    id: 'lotte-premium-outlets-busan',
    name: '롯데프리미엄아울렛 부산점',
    type: 'shopping',
    lat: 35.1776,
    lng: 129.1920,
    address: '부산광역시 기장군 기장읍 기장해안로 147',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-12',
    source: 'user',
  },

  // ─── 인천 ───────────────────────────────────────────────
  {
    id: 'incheon-airport-t1',
    name: '인천국제공항 제1터미널',
    type: 'building',
    lat: 37.4491,
    lng: 126.4500,
    address: '인천광역시 중구 공항로 272',
    accessibility: {
      elevator: { available: true, floors: 'B2~5F', note: '전 층 복수 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '체크인 키오스크 음성·점자 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '무료 휠체어 서비스 제공' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-20',
    source: 'official',
  },
  {
    id: 'incheon-station',
    name: '인천역',
    type: 'subway',
    lat: 37.4740,
    lng: 126.6162,
    address: '인천광역시 중구 제물량로 183',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-20',
    source: 'osm',
  },
  {
    id: 'incheon-arts-center',
    name: '인천문화예술회관',
    type: 'cultural',
    lat: 37.4622,
    lng: 126.7050,
    address: '인천광역시 남동구 예술로 90',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-15',
    source: 'user',
  },

  // ─── 대구 ───────────────────────────────────────────────
  {
    id: 'daegu-station',
    name: '동대구역',
    type: 'subway',
    lat: 35.8799,
    lng: 128.6281,
    address: '대구광역시 동구 동대구로 550',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'daegu-national-museum',
    name: '국립대구박물관',
    type: 'cultural',
    lat: 35.8368,
    lng: 128.5990,
    address: '대구광역시 수성구 청호로 321',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },
  {
    id: 'daegu-dongseongno',
    name: '동성로 지하도상가',
    type: 'shopping',
    lat: 35.8699,
    lng: 128.5958,
    address: '대구광역시 중구 동성로 지하상가',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 1F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'limited', note: '일부 구간 경사로 미비' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-20',
    source: 'user',
  },

  // ─── 광주 ───────────────────────────────────────────────
  {
    id: 'gwangju-station',
    name: '광주송정역',
    type: 'subway',
    lat: 35.1396,
    lng: 126.7937,
    address: '광주광역시 광산구 송정공원로 1',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-25',
    source: 'official',
  },
  {
    id: 'gwangju-national-museum',
    name: '국립광주박물관',
    type: 'cultural',
    lat: 35.1537,
    lng: 126.9020,
    address: '광주광역시 북구 하서로 110',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-10',
    source: 'official',
  },
  {
    id: 'gwangju-5-18-memorial',
    name: '5·18민주화운동기록관',
    type: 'cultural',
    lat: 35.1483,
    lng: 126.9144,
    address: '광주광역시 동구 금남로 221',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-05',
    source: 'user',
  },

  // ─── 대전 ───────────────────────────────────────────────
  {
    id: 'daejeon-station',
    name: '대전역',
    type: 'subway',
    lat: 36.3322,
    lng: 127.4345,
    address: '대전광역시 동구 중앙로 215',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },
  {
    id: 'expo-science-park',
    name: '엑스포과학공원',
    type: 'public',
    lat: 36.3742,
    lng: 127.3850,
    address: '대전광역시 유성구 대덕대로 480',
    accessibility: {
      elevator: { available: true, floors: '1F~3F', note: '주요 전시관 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-25',
    source: 'user',
  },

  // ─── 수원 ───────────────────────────────────────────────
  {
    id: 'hwaseong-fortress',
    name: '수원화성',
    type: 'cultural',
    lat: 37.2851,
    lng: 127.0139,
    address: '경기도 수원시 팔달구 행궁로 11',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false, note: '입장권 발매기 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '성벽 순환로 계단 다수, 우회 평지 경로 있음' },
      wheelchair: { accessible: 'limited', note: '행궁 내부 일부 구역 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-10',
    source: 'user',
  },
  {
    id: 'suwon-station',
    name: '수원역',
    type: 'subway',
    lat: 37.2655,
    lng: 127.0005,
    address: '경기도 수원시 팔달구 매산로1가 1',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-30',
    source: 'official',
  },

  // ─── 전주 ───────────────────────────────────────────────
  {
    id: 'jeonju-hanok-village',
    name: '전주한옥마을',
    type: 'cultural',
    lat: 35.8146,
    lng: 127.1467,
    address: '전북 전주시 완산구 기린대로 99',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: false, note: '골목 비탈 다수, 일부 완만한 우회 경로 있음' },
      wheelchair: { accessible: 'limited', note: '메인 거리는 평지, 좁은 골목 접근 어려움' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-01',
    source: 'user',
  },
  {
    id: 'jeonju-national-museum',
    name: '국립전주박물관',
    type: 'cultural',
    lat: 35.8238,
    lng: 127.1100,
    address: '전북 전주시 완산구 쑥고개로 249',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },

  // ─── 경주 ───────────────────────────────────────────────
  {
    id: 'gyeongju-national-museum',
    name: '국립경주박물관',
    type: 'cultural',
    lat: 35.8341,
    lng: 129.2243,
    address: '경북 경주시 일정로 186',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-20',
    source: 'official',
  },
  {
    id: 'bulguksa',
    name: '불국사',
    type: 'cultural',
    lat: 35.7898,
    lng: 129.3316,
    address: '경북 경주시 불국로 385',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 30, ramp: false, note: '청운교·백운교 등 가파른 계단 다수, 우회 경사로 있음' },
      wheelchair: { accessible: 'limited', note: '일부 평지 경내 접근 가능, 사전 문의 필요' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-25',
    source: 'user',
  },

  // ─── 제주 ───────────────────────────────────────────────
  {
    id: 'jeju-airport',
    name: '제주국제공항',
    type: 'building',
    lat: 33.5113,
    lng: 126.4928,
    address: '제주특별자치도 제주시 공항로 2',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '무료 휠체어 대여 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'jeju-national-museum',
    name: '국립제주박물관',
    type: 'cultural',
    lat: 33.5135,
    lng: 126.5300,
    address: '제주특별자치도 제주시 일주동로 17',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'jeju-teddy-bear-museum',
    name: '제주테디베어뮤지엄',
    type: 'cultural',
    lat: 33.2451,
    lng: 126.4124,
    address: '제주특별자치도 서귀포시 중문관광로 110번길 31',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-08',
    source: 'user',
  },

  // ─── 강릉 ───────────────────────────────────────────────
  {
    id: 'gangneung-station',
    name: '강릉역',
    type: 'subway',
    lat: 37.7878,
    lng: 128.9387,
    address: '강원특별자치도 강릉시 경강로 2048',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-18',
    source: 'official',
  },
  {
    id: 'gyeongpodae',
    name: '경포대',
    type: 'public',
    lat: 37.8071,
    lng: 128.9000,
    address: '강원특별자치도 강릉시 경포로 365',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '전망대 계단, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '호수 주변 산책로는 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-06-05',
    source: 'user',
  },

  // ─── 창원 ───────────────────────────────────────────────
  {
    id: 'changwon-station',
    name: '창원중앙역',
    type: 'subway',
    lat: 35.2539,
    lng: 128.6642,
    address: '경남 창원시 의창구 중앙대로 252',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-22',
    source: 'official',
  },

  // ─── 춘천 ───────────────────────────────────────────────
  {
    id: 'chuncheon-station',
    name: '춘천역',
    type: 'subway',
    lat: 37.8663,
    lng: 127.7326,
    address: '강원특별자치도 춘천시 동내면 외솔길 109',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-12',
    source: 'osm',
  },

  // ─── 울산 ───────────────────────────────────────────────
  {
    id: 'ulsan-station',
    name: '울산역(KTX)',
    type: 'subway',
    lat: 35.5556,
    lng: 129.1802,
    address: '울산광역시 울주군 삼남읍 울산역로 125',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-30',
    source: 'official',
  },
  {
    id: 'ulsan-museum',
    name: '울산박물관',
    type: 'cultural',
    lat: 35.5380,
    lng: 129.3119,
    address: '울산광역시 남구 두왕로 277',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-08',
    source: 'user',
  },

  // ─── 성남·분당 ────────────────────────────────────────
  {
    id: 'pangyo-station',
    name: '판교역',
    type: 'subway',
    lat: 37.3943,
    lng: 127.1111,
    address: '경기도 성남시 분당구 판교역로 160',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-08',
    source: 'official',
  },

  // ─── 고양 ────────────────────────────────────────────
  {
    id: 'ilsan-western-lake',
    name: '일산 호수공원',
    type: 'public',
    lat: 37.6757,
    lng: 126.7717,
    address: '경기도 고양시 일산동구 호수로 595',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 전체 평탄한 보행로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-22',
    source: 'user',
  },

  // ─── 청주 ────────────────────────────────────────────
  {
    id: 'cheongju-station',
    name: '오송역',
    type: 'subway',
    lat: 36.6227,
    lng: 127.3128,
    address: '충북 청주시 흥덕구 오송읍 오송가락로 123',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'cheongju-national-museum',
    name: '국립청주박물관',
    type: 'cultural',
    lat: 36.6433,
    lng: 127.4910,
    address: '충북 청주시 상당구 명암로 143',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-03',
    source: 'official',
  },

  // ─── 목포 ────────────────────────────────────────────
  {
    id: 'mokpo-national-maritime',
    name: '국립해양문화재연구소',
    type: 'cultural',
    lat: 34.7933,
    lng: 126.3811,
    address: '전남 목포시 남농로 136',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-06-28',
    source: 'user',
  },

  // ─── 안동 ────────────────────────────────────────────
  {
    id: 'hahoe-village',
    name: '안동하회마을',
    type: 'cultural',
    lat: 36.5393,
    lng: 128.5196,
    address: '경북 안동시 풍천면 전서로 186',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: false, note: '마을 내 비포장·비탈길 다수' },
      wheelchair: { accessible: 'limited', note: '메인 진입로 평탄, 마을 내부 일부 어려움' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-18',
    source: 'user',
  },
];
