import { AccessibilityLocation } from './types';

export const sampleLocations: AccessibilityLocation[] = [
  {
    id: 'seoul-station',
    name: '서울역',
    type: 'subway',
    lat: 37.5547,
    lng: 126.9707,
    address: '서울특별시 용산구 한강대로 405',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F', note: '1·4호선, KTX 모든 층 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '승차권 발매기 음성 안내 지원' },
      steps: { hasSteps: false, ramp: true, note: '주 출입구 경사로 완비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-10',
    source: 'official',
  },
  {
    id: 'gangnam-station',
    name: '강남역',
    type: 'subway',
    lat: 37.4979,
    lng: 127.0276,
    address: '서울특별시 강남구 강남대로 396',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F', note: '2호선 상·하행 모두 엘리베이터 이용 가능' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false, note: '일부 발매기만 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'hongik-station',
    name: '홍대입구역',
    type: 'subway',
    lat: 37.5572,
    lng: 126.9245,
    address: '서울특별시 마포구 양화로 160',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: false, note: '음성 안내 미지원, 터치스크린만 가능' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'gwanghwamun-square',
    name: '광화문광장',
    type: 'public',
    lat: 37.5752,
    lng: 126.9769,
    address: '서울특별시 종로구 세종대로 172',
    accessibility: {
      elevator: { available: false, note: '지하 공간 없음' },
      kiosk: { available: true, voiceSupport: false, note: '안내 키오스크 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 3, ramp: true, note: '광장 진입 단차 3cm 이하, 경사로 있음' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'user',
  },
  {
    id: 'severance-hospital',
    name: '세브란스병원',
    type: 'hospital',
    lat: 37.5622,
    lng: 126.9405,
    address: '서울특별시 서대문구 연세로 50-1',
    accessibility: {
      elevator: { available: true, floors: 'B5~지상 21F', note: '본관·별관 모든 층 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '원무 접수 키오스크 음성·대형글씨 완비' },
      steps: { hasSteps: false, ramp: true, note: '주출입구 자동문·경사로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'gyeongbokgung',
    name: '경복궁',
    type: 'cultural',
    lat: 37.5796,
    lng: 126.9770,
    address: '서울특별시 종로구 사직로 161',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false, note: '입장권 발매 키오스크, 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 15, ramp: false, note: '정문(흥례문) 계단 단차 약 15cm, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '일부 구역만 접근 가능, 사전 문의 권장' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-20',
    source: 'user',
  },
  {
    id: 'itaewon-station',
    name: '이태원역',
    type: 'subway',
    lat: 37.5345,
    lng: 126.9943,
    address: '서울특별시 용산구 이태원로 177',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-01',
    source: 'osm',
  },
  {
    id: 'lotte-world-tower',
    name: '롯데월드타워',
    type: 'building',
    lat: 37.5126,
    lng: 127.1026,
    address: '서울특별시 송파구 올림픽로 300',
    accessibility: {
      elevator: { available: true, floors: 'B7~123F', note: '고속 엘리베이터 및 장애인용 별도 엘리베이터 운영' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-15',
    source: 'official',
  },
  {
    id: 'national-museum',
    name: '국립중앙박물관',
    type: 'cultural',
    lat: 37.5240,
    lng: 126.9799,
    address: '서울특별시 용산구 서빙고로 137',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '안내·티켓 키오스크 완전 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'sinchon-station',
    name: '신촌역',
    type: 'subway',
    lat: 37.5551,
    lng: 126.9368,
    address: '서울특별시 서대문구 신촌로 83',
    accessibility: {
      elevator: { available: false, note: '엘리베이터 미설치, 에스컬레이터만 운영' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '출구 계단 단차 약 20cm, 경사로 없음' },
      wheelchair: { accessible: 'no', note: '휠체어 이용 매우 어려움, 인근 홍대입구역 이용 권장' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-08-05',
    source: 'user',
  },
  {
    id: 'dongdaemun-dps',
    name: '동대문디자인플라자(DDP)',
    type: 'cultural',
    lat: 37.5669,
    lng: 127.0095,
    address: '서울특별시 중구 을지로 281',
    accessibility: {
      elevator: { available: true, floors: 'B3~4F', note: '전 층 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'official',
  },
  {
    id: 'seoul-arts-center',
    name: '예술의전당',
    type: 'cultural',
    lat: 37.4773,
    lng: 127.0144,
    address: '서울특별시 서초구 남부순환로 2406',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: true, voiceSupport: false, note: '티켓 발권 키오스크, 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'seoul-asan-hospital',
    name: '서울아산병원',
    type: 'hospital',
    lat: 37.5270,
    lng: 127.1083,
    address: '서울특별시 송파구 올림픽로43길 88',
    accessibility: {
      elevator: { available: true, floors: 'B5~28F', note: '각 동 별도 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },

  {
    id: 'gangnam-gu-office',
    name: '강남구청',
    type: 'building',
    lat: 37.5172,
    lng: 127.0473,
    address: '서울특별시 강남구 학동로 426',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '민원 발급 키오스크 완전 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'samsung-station',
    name: '삼성역',
    type: 'subway',
    lat: 37.5088,
    lng: 127.0631,
    address: '서울특별시 강남구 테헤란로 213',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'yeoksam-station',
    name: '역삼역',
    type: 'subway',
    lat: 37.5007,
    lng: 127.0362,
    address: '서울특별시 강남구 강남대로 316',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'seonleung-station',
    name: '선릉역',
    type: 'subway',
    lat: 37.5047,
    lng: 127.0491,
    address: '서울특별시 강남구 테헤란로 411',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'apgujeong-rodeo',
    name: '압구정로데오역',
    type: 'subway',
    lat: 37.5274,
    lng: 127.0399,
    address: '서울특별시 강남구 선릉로 720',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'user',
  },
  {
    id: 'gangnam-severance',
    name: '강남세브란스병원',
    type: 'hospital',
    lat: 37.4924,
    lng: 127.0783,
    address: '서울특별시 강남구 언주로 211',
    accessibility: {
      elevator: { available: true, floors: 'B5~20F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },
  {
    id: 'samsung-medical-center',
    name: '삼성서울병원',
    type: 'hospital',
    lat: 37.4885,
    lng: 127.0853,
    address: '서울특별시 강남구 일원로 81',
    accessibility: {
      elevator: { available: true, floors: 'B5~22F', note: '본관·별관·암센터 전 층 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-12',
    source: 'official',
  },
  {
    id: 'gangnam-cgv',
    name: 'CGV 강남',
    type: 'cultural',
    lat: 37.4970,
    lng: 127.0276,
    address: '서울특별시 강남구 강남대로 438',
    accessibility: {
      elevator: { available: true, floors: '1F~9F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '발권 키오스크 음성·대형글씨 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 좌석 사전 예약 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'hyundai-motors-studio-gangnam',
    name: '현대모터스튜디오 서울',
    type: 'cultural',
    lat: 37.5068,
    lng: 127.0559,
    address: '서울특별시 강남구 테헤란로 517',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'gangnam-lotte-cinema',
    name: '롯데시네마 강남',
    type: 'cultural',
    lat: 37.5002,
    lng: 127.0267,
    address: '서울특별시 강남구 강남대로 542',
    accessibility: {
      elevator: { available: true, floors: '1F~8F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'user',
  },
  {
    id: 'gangnam-post-office',
    name: '강남우체국',
    type: 'building',
    lat: 37.5009,
    lng: 127.0254,
    address: '서울특별시 강남구 강남대로 622',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-20',
    source: 'user',
  },
  {
    id: 'gangnam-tax-office',
    name: '강남세무서',
    type: 'building',
    lat: 37.5089,
    lng: 127.0407,
    address: '서울특별시 강남구 논현로 430',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },
  {
    id: 'sinnonhyeon-station',
    name: '신논현역',
    type: 'subway',
    lat: 37.5047,
    lng: 127.0250,
    address: '서울특별시 강남구 강남대로 지하 566',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'gu-banhapdan',
    name: '학동역',
    type: 'subway',
    lat: 37.5165,
    lng: 127.0388,
    address: '서울특별시 강남구 논현로 430',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-15',
    source: 'osm',
  },
  {
    id: 'daechi-station',
    name: '대치역',
    type: 'subway',
    lat: 37.4944,
    lng: 127.0607,
    address: '서울특별시 강남구 남부순환로 2933',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-05',
    source: 'osm',
  },
  {
    id: 'gangnam-gu-library',
    name: '강남구립도서관',
    type: 'cultural',
    lat: 37.5085,
    lng: 127.0557,
    address: '서울특별시 강남구 삼성로 212',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-18',
    source: 'user',
  },
  {
    id: 'bongeunsa',
    name: '봉은사',
    type: 'cultural',
    lat: 37.5148,
    lng: 127.0589,
    address: '서울특별시 강남구 봉은사로 531',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true, note: '경내 일부 경사로 정비' },
      wheelchair: { accessible: 'limited', note: '중심 법당 접근 가능, 외곽 전각 어려움' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-25',
    source: 'user',
  },

  {
    id: 'yongsan-station',
    name: '용산역',
    type: 'subway',
    lat: 37.5298,
    lng: 126.9649,
    address: '서울특별시 용산구 한강대로 23길 55',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 3F', note: 'KTX·경의중앙선·1호선 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-08',
    source: 'official',
  },
  {
    id: 'national-museum-of-korea',
    name: '국립한글박물관',
    type: 'cultural',
    lat: 37.5243,
    lng: 126.9800,
    address: '서울특별시 용산구 서빙고로 139',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-14',
    source: 'official',
  },
  {
    id: 'war-memorial-korea',
    name: '전쟁기념관',
    type: 'cultural',
    lat: 37.5362,
    lng: 126.9771,
    address: '서울특별시 용산구 이태원로 29',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },
  {
    id: 'namsan-cable-car',
    name: '남산케이블카',
    type: 'public',
    lat: 37.5513,
    lng: 126.9800,
    address: '서울특별시 중구 소파로 83',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 15, ramp: false, note: '탑승장 계단, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '케이블카 탑승 가능하나 접근로 계단 있음' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-05',
    source: 'user',
  },
  {
    id: 'namsan-n-tower',
    name: 'N서울타워',
    type: 'building',
    lat: 37.5512,
    lng: 126.9882,
    address: '서울특별시 용산구 남산공원길 105',
    accessibility: {
      elevator: { available: true, floors: '1F~5F', note: '전망대 전용 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-12',
    source: 'official',
  },
  {
    id: 'haebangchon-hospital',
    name: '순천향대학교 서울병원',
    type: 'hospital',
    lat: 37.5393,
    lng: 126.9679,
    address: '서울특별시 용산구 대사관로 59',
    accessibility: {
      elevator: { available: true, floors: 'B3~12F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'ichon-station',
    name: '이촌역',
    type: 'subway',
    lat: 37.5225,
    lng: 126.9716,
    address: '서울특별시 용산구 이촌로 72',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-25',
    source: 'osm',
  },
  {
    id: 'yongsan-family-park',
    name: '용산가족공원',
    type: 'public',
    lat: 37.5242,
    lng: 126.9773,
    address: '서울특별시 용산구 서빙고로 185',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 전체 평탄한 산책로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-30',
    source: 'user',
  },
  {
    id: 'hangangjin-station',
    name: '한강진역',
    type: 'subway',
    lat: 37.5391,
    lng: 126.9884,
    address: '서울특별시 용산구 이태원로 257',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-02',
    source: 'osm',
  },
  {
    id: 'itaewon-global-village-center',
    name: '이태원 글로벌빌리지센터',
    type: 'public',
    lat: 37.5340,
    lng: 126.9940,
    address: '서울특별시 용산구 이태원로 177',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 8, ramp: true },
      wheelchair: { accessible: 'limited' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-15',
    source: 'user',
  },

  {
    id: 'hapjeong-station',
    name: '합정역',
    type: 'subway',
    lat: 37.5498,
    lng: 126.9147,
    address: '서울특별시 마포구 양화로 93',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'sangsu-station',
    name: '상수역',
    type: 'subway',
    lat: 37.5481,
    lng: 126.9231,
    address: '서울특별시 마포구 와우산로 98',
    accessibility: {
      elevator: { available: false, note: '엘리베이터 미설치' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false },
      wheelchair: { accessible: 'no', note: '인근 합정역 이용 권장' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-12',
    source: 'user',
  },
  {
    id: 'mapo-gu-office',
    name: '마포구청',
    type: 'building',
    lat: 37.5581,
    lng: 126.9087,
    address: '서울특별시 마포구 월드컵로 212',
    accessibility: {
      elevator: { available: true, floors: 'B1~9F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-20',
    source: 'official',
  },
  {
    id: 'seoulworld-cup-stadium',
    name: '서울월드컵경기장',
    type: 'public',
    lat: 37.5683,
    lng: 126.8973,
    address: '서울특별시 마포구 월드컵로 240',
    accessibility: {
      elevator: { available: true, floors: '1F~5F', note: '주 게이트별 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 관람석 별도 구역' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-10',
    source: 'official',
  },
  {
    id: 'hongik-univ-station-2',
    name: '홍대입구역 2호선',
    type: 'subway',
    lat: 37.5573,
    lng: 126.9246,
    address: '서울특별시 마포구 양화로 160',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-25',
    source: 'official',
  },
  {
    id: 'aha-park-hongdae',
    name: '홍대 놀이터(AHA Park)',
    type: 'public',
    lat: 37.5534,
    lng: 126.9237,
    address: '서울특별시 마포구 와우산로21길',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: false, accessible: false },
    },
    lastUpdated: '2024-07-01',
    source: 'user',
  },
  {
    id: 'mapo-culture-foundation',
    name: '마포문화재단 마포아트센터',
    type: 'cultural',
    lat: 37.5588,
    lng: 126.9115,
    address: '서울특별시 마포구 월드컵로 279',
    accessibility: {
      elevator: { available: true, floors: 'B2~5F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },
  {
    id: 'mapo-samsung-hospital',
    name: '이화여자대학교 서울병원',
    type: 'hospital',
    lat: 37.5563,
    lng: 126.9444,
    address: '서울특별시 마포구 도화길 41',
    accessibility: {
      elevator: { available: true, floors: 'B3~12F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },
  {
    id: 'cgv-hongdae',
    name: 'CGV 홍대',
    type: 'cultural',
    lat: 37.5561,
    lng: 126.9230,
    address: '서울특별시 마포구 양화로 188',
    accessibility: {
      elevator: { available: true, floors: '1F~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'hongdae-playground-park',
    name: '홍대 걷고싶은거리',
    type: 'public',
    lat: 37.5544,
    lng: 126.9226,
    address: '서울특별시 마포구 어울마당로',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '보행자 전용도로 평탄 정비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-12',
    source: 'user',
  },

  {
    id: 'konkuk-univ-station',
    name: '건대입구역',
    type: 'subway',
    lat: 37.5403,
    lng: 127.0700,
    address: '서울특별시 광진구 능동로 248',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },
  {
    id: 'konkuk-university-hospital',
    name: '건국대학교병원',
    type: 'hospital',
    lat: 37.5378,
    lng: 127.0758,
    address: '서울특별시 광진구 능동로 120-1',
    accessibility: {
      elevator: { available: true, floors: 'B4~16F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },
  {
    id: 'lotte-world-adventure',
    name: '롯데월드 어드벤처',
    type: 'public',
    lat: 37.5111,
    lng: 127.0983,
    address: '서울특별시 송파구 올림픽로 240',
    accessibility: {
      elevator: { available: true, floors: 'B2~4F', note: '실내 어드벤처 전 층 연결' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 입장 게이트 운영, 일부 탑승 제한 있음' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-28',
    source: 'official',
  },
  {
    id: 'guui-station',
    name: '구의역',
    type: 'subway',
    lat: 37.5445,
    lng: 127.0944,
    address: '서울특별시 광진구 자양로 185',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'osm',
  },
  {
    id: 'gwangjin-gu-office',
    name: '광진구청',
    type: 'building',
    lat: 37.5385,
    lng: 127.0822,
    address: '서울특별시 광진구 자양로 117',
    accessibility: {
      elevator: { available: true, floors: 'B1~6F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'children-grand-park',
    name: '어린이대공원',
    type: 'public',
    lat: 37.5486,
    lng: 127.0810,
    address: '서울특별시 광진구 능동로 216',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 내 주요 동선 경사로 완비' },
      wheelchair: { accessible: 'yes', note: '휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'official',
  },
  {
    id: 'ttukseom-hangang-park',
    name: '뚝섬한강공원',
    type: 'public',
    lat: 37.5290,
    lng: 127.0670,
    address: '서울특별시 광진구 강변북로 139',
    accessibility: {
      elevator: { available: true, floors: '1F~3F', note: '접근 육교 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-05',
    source: 'user',
  },
  {
    id: 'jayang-station',
    name: '자양역(5호선)',
    type: 'subway',
    lat: 37.5428,
    lng: 127.0942,
    address: '서울특별시 광진구 자양로 260',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-22',
    source: 'osm',
  },

  {
    id: 'ewha-campus',
    name: '이화여자대학교 ECC',
    type: 'cultural',
    lat: 37.5626,
    lng: 126.9469,
    address: '서울특별시 서대문구 이화여대길 52',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'seodaemun-independent-hall',
    name: '서대문독립공원(형무소역사관)',
    type: 'cultural',
    lat: 37.5720,
    lng: 126.9590,
    address: '서울특별시 서대문구 통일로 251',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true },
      wheelchair: { accessible: 'limited', note: '역사관 건물 내부 계단 많음, 일부 우회 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-28',
    source: 'user',
  },
  {
    id: 'sinchon-yonsei-hospital',
    name: '신촌 세브란스병원',
    type: 'hospital',
    lat: 37.5622,
    lng: 126.9405,
    address: '서울특별시 서대문구 연세로 50-1',
    accessibility: {
      elevator: { available: true, floors: 'B5~21F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'seodaemun-natural-history',
    name: '서대문자연사박물관',
    type: 'cultural',
    lat: 37.5783,
    lng: 126.9355,
    address: '서울특별시 서대문구 연희로32길 51',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-20',
    source: 'official',
  },

  {
    id: 'seongsu-station',
    name: '성수역',
    type: 'subway',
    lat: 37.5447,
    lng: 127.0560,
    address: '서울특별시 성동구 뚝섬로 425',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-03',
    source: 'official',
  },
  {
    id: 'wangsimni-station',
    name: '왕십리역',
    type: 'subway',
    lat: 37.5614,
    lng: 127.0375,
    address: '서울특별시 성동구 왕십리광장로 17',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 2F', note: '2호선·5호선·경의중앙선 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },
  {
    id: 'sungdong-gu-office',
    name: '성동구청',
    type: 'building',
    lat: 37.5635,
    lng: 127.0367,
    address: '서울특별시 성동구 고산자로 270',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'seoul-forest',
    name: '서울숲',
    type: 'public',
    lat: 37.5443,
    lng: 127.0374,
    address: '서울특별시 성동구 뚝섬로 273',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '주요 산책로 평탄 정비' },
      wheelchair: { accessible: 'yes', note: '휠체어 대여 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },

  {
    id: 'sillim-station',
    name: '신림역',
    type: 'subway',
    lat: 37.4844,
    lng: 126.9294,
    address: '서울특별시 관악구 신림로 249',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'official',
  },
  {
    id: 'gwanak-gu-office',
    name: '관악구청',
    type: 'building',
    lat: 37.4776,
    lng: 126.9516,
    address: '서울특별시 관악구 관악로 145',
    accessibility: {
      elevator: { available: true, floors: 'B1~6F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },

  {
    id: 'nowon-station',
    name: '노원역',
    type: 'subway',
    lat: 37.6554,
    lng: 127.0562,
    address: '서울특별시 노원구 동일로 1414',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F', note: '4호선·7호선 환승 가능' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'nowon-gu-office',
    name: '노원구청',
    type: 'building',
    lat: 37.6544,
    lng: 127.0563,
    address: '서울특별시 노원구 노해로 437',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },
  {
    id: 'junggye-station',
    name: '중계역',
    type: 'subway',
    lat: 37.6350,
    lng: 127.0680,
    address: '서울특별시 노원구 동일로 1430',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-18',
    source: 'osm',
  },

  {
    id: 'jonggak-station',
    name: '종각역',
    type: 'subway',
    lat: 37.5702,
    lng: 126.9822,
    address: '서울특별시 종로구 종로 지하31',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },
  {
    id: 'jongno3ga-station',
    name: '종로3가역',
    type: 'subway',
    lat: 37.5706,
    lng: 126.9918,
    address: '서울특별시 종로구 종로 지하130',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F', note: '1호선·3호선·5호선 연결 엘리베이터' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'cheonggyecheon-stream',
    name: '청계천',
    type: 'public',
    lat: 37.5695,
    lng: 126.9795,
    address: '서울특별시 종로구 청계천로 1',
    accessibility: {
      elevator: { available: true, floors: '지상~하부 산책로', note: '주요 접근 지점 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true, note: '하천 접근 계단, 주요 구간 경사로 병행' },
      wheelchair: { accessible: 'yes', note: '하부 산책로 전체 평탄' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'myeongdong-station',
    name: '명동역',
    type: 'subway',
    lat: 37.5634,
    lng: 126.9862,
    address: '서울특별시 중구 명동길 지하14',
    accessibility: {
      elevator: { available: true, floors: 'B3~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-28',
    source: 'official',
  },
  {
    id: 'seoul-city-hall',
    name: '서울시청',
    type: 'building',
    lat: 37.5662,
    lng: 126.9779,
    address: '서울특별시 중구 세종대로 110',
    accessibility: {
      elevator: { available: true, floors: 'B3~13F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-30',
    source: 'official',
  },
  {
    id: 'deoksugung',
    name: '덕수궁',
    type: 'cultural',
    lat: 37.5659,
    lng: 126.9751,
    address: '서울특별시 중구 세종대로 99',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true, note: '정문 경사로 설치, 내부 일부 비포장' },
      wheelchair: { accessible: 'limited', note: '정원 및 석조전 주변 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-28',
    source: 'user',
  },

  {
    id: 'jamsil-station',
    name: '잠실역',
    type: 'subway',
    lat: 37.5133,
    lng: 127.1002,
    address: '서울특별시 송파구 올림픽로 지하265',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F', note: '2호선·8호선 환승 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-28',
    source: 'official',
  },
  {
    id: 'olympic-park',
    name: '올림픽공원',
    type: 'public',
    lat: 37.5207,
    lng: 127.1219,
    address: '서울특별시 송파구 올림픽로 424',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 내 주요 도로 평탄, 경사로 완비' },
      wheelchair: { accessible: 'yes', note: '휠체어 대여 서비스 운영' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-22',
    source: 'official',
  },

  {
    id: 'yeouido-station',
    name: '여의도역',
    type: 'subway',
    lat: 37.5216,
    lng: 126.9247,
    address: '서울특별시 영등포구 여의나루로 지하53',
    accessibility: {
      elevator: { available: true, floors: 'B4~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'yeouido-hangang-park',
    name: '여의도한강공원',
    type: 'public',
    lat: 37.5284,
    lng: 126.9323,
    address: '서울특별시 영등포구 여의동로 330',
    accessibility: {
      elevator: { available: true, floors: '지상~지하 연결', note: '지하차도 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'national-assembly',
    name: '국회의사당',
    type: 'building',
    lat: 37.5322,
    lng: 126.9147,
    address: '서울특별시 영등포구 의사당대로 1',
    accessibility: {
      elevator: { available: true, floors: 'B2~6F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },

  {
    id: 'yeongdeungpo-station',
    name: '영등포역',
    type: 'subway',
    lat: 37.5158,
    lng: 126.9072,
    address: '서울특별시 영등포구 경인로 846',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },

  {
    id: 'busan-station',
    name: '부산역',
    type: 'subway',
    lat: 35.1145,
    lng: 129.0420,
    address: '부산광역시 동구 중앙대로 206',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F', note: 'KTX·무궁화 연결 전 층' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-10',
    source: 'official',
  },
  {
    id: 'haeundae-beach',
    name: '해운대해수욕장',
    type: 'public',
    lat: 35.1588,
    lng: 129.1603,
    address: '부산광역시 해운대구 해운대해변로 264',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '해변 진입 경사로 완비' },
      wheelchair: { accessible: 'yes', note: '해변 전용 휠체어 무료 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-15',
    source: 'user',
  },
  {
    id: 'busan-cinema-center',
    name: '영화의전당',
    type: 'cultural',
    lat: 35.1598,
    lng: 129.1221,
    address: '부산광역시 해운대구 수영강변대로 120',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'busan-national-museum',
    name: '국립부산박물관',
    type: 'cultural',
    lat: 35.1070,
    lng: 129.0896,
    address: '부산광역시 남구 유엔평화로 63',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-30',
    source: 'official',
  },
  {
    id: 'busan-university-hospital',
    name: '부산대학교병원',
    type: 'hospital',
    lat: 35.1262,
    lng: 129.0219,
    address: '부산광역시 서구 구덕로 179',
    accessibility: {
      elevator: { available: true, floors: 'B2~15F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },

  {
    id: 'incheon-airport-t1',
    name: '인천국제공항 제1터미널',
    type: 'building',
    lat: 37.4491,
    lng: 126.4500,
    address: '인천광역시 중구 공항로 272',
    accessibility: {
      elevator: { available: true, floors: 'B2~5F', note: '전 층 복수 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '체크인 키오스크 음성·점자 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '무료 휠체어 서비스 제공' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-20',
    source: 'official',
  },
  {
    id: 'incheon-station',
    name: '인천역',
    type: 'subway',
    lat: 37.4740,
    lng: 126.6162,
    address: '인천광역시 중구 제물량로 183',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-20',
    source: 'osm',
  },
  {
    id: 'incheon-arts-center',
    name: '인천문화예술회관',
    type: 'cultural',
    lat: 37.4622,
    lng: 126.7050,
    address: '인천광역시 남동구 예술로 90',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-15',
    source: 'user',
  },

  {
    id: 'daegu-station',
    name: '동대구역',
    type: 'subway',
    lat: 35.8799,
    lng: 128.6281,
    address: '대구광역시 동구 동대구로 550',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'daegu-national-museum',
    name: '국립대구박물관',
    type: 'cultural',
    lat: 35.8368,
    lng: 128.5990,
    address: '대구광역시 수성구 청호로 321',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },

  {
    id: 'gwangju-songjeong-station',
    name: '광주송정역',
    type: 'subway',
    lat: 35.1396,
    lng: 126.7937,
    address: '광주광역시 광산구 송정공원로 1',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-25',
    source: 'official',
  },
  {
    id: 'gwangju-national-museum',
    name: '국립광주박물관',
    type: 'cultural',
    lat: 35.1537,
    lng: 126.9020,
    address: '광주광역시 북구 하서로 110',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-10',
    source: 'official',
  },
  {
    id: 'gwangju-5-18-memorial',
    name: '5·18민주화운동기록관',
    type: 'cultural',
    lat: 35.1483,
    lng: 126.9144,
    address: '광주광역시 동구 금남로 221',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-05',
    source: 'user',
  },

  {
    id: 'gwangju-terminal',
    name: '광주종합버스터미널',
    type: 'building',
    lat: 35.1462,
    lng: 126.9258,
    address: '광주광역시 서구 무진대로 533',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '승차권 발매 키오스크 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },
  {
    id: 'gwangju-airport',
    name: '광주공항',
    type: 'building',
    lat: 35.1264,
    lng: 126.8088,
    address: '광주광역시 광산구 공항로 231',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '무료 휠체어 대여' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-20',
    source: 'official',
  },
  {
    id: 'gwangju-gu-office-seo',
    name: '광주 서구청',
    type: 'building',
    lat: 35.1523,
    lng: 126.8895,
    address: '광주광역시 서구 내방로 111',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-08',
    source: 'official',
  },
  {
    id: 'gwangju-gu-office-buk',
    name: '광주 북구청',
    type: 'building',
    lat: 35.1740,
    lng: 126.9120,
    address: '광주광역시 북구 용봉로 120',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-22',
    source: 'official',
  },
  {
    id: 'gwangju-gu-office-dong',
    name: '광주 동구청',
    type: 'building',
    lat: 35.1462,
    lng: 126.9239,
    address: '광주광역시 동구 서남로 1',
    accessibility: {
      elevator: { available: true, floors: 'B1~6F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-10',
    source: 'official',
  },
  {
    id: 'gwangju-gu-office-nam',
    name: '광주 남구청',
    type: 'building',
    lat: 35.1337,
    lng: 126.9022,
    address: '광주광역시 남구 중앙로 15',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-28',
    source: 'official',
  },
  {
    id: 'gwangju-gu-office-gwangsan',
    name: '광주 광산구청',
    type: 'building',
    lat: 35.1396,
    lng: 126.7937,
    address: '광주광역시 광산구 광산로 29번길 10',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'official',
  },
  {
    id: 'chonnam-national-univ-hospital',
    name: '전남대학교병원',
    type: 'hospital',
    lat: 35.1744,
    lng: 126.9102,
    address: '광주광역시 동구 학동로 42번길 42',
    accessibility: {
      elevator: { available: true, floors: 'B4~15F', note: '본관·별관 전 층 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'chosun-univ-hospital',
    name: '조선대학교병원',
    type: 'hospital',
    lat: 35.1406,
    lng: 126.9278,
    address: '광주광역시 동구 필문대로 365',
    accessibility: {
      elevator: { available: true, floors: 'B3~14F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'gwangju-christian-hospital',
    name: '광주기독병원',
    type: 'hospital',
    lat: 35.1461,
    lng: 126.9094,
    address: '광주광역시 남구 양림로 37',
    accessibility: {
      elevator: { available: true, floors: 'B2~10F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'user',
  },
  {
    id: 'gwangju-arts-center',
    name: '광주문화예술회관',
    type: 'cultural',
    lat: 35.1616,
    lng: 126.8869,
    address: '광주광역시 서구 내방로 402',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'official',
  },
  {
    id: 'gwangju-biennale-hall',
    name: '광주비엔날레전시관',
    type: 'cultural',
    lat: 35.1588,
    lng: 126.8960,
    address: '광주광역시 북구 비엔날레로 111',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'gwangju-museum-art',
    name: '광주시립미술관',
    type: 'cultural',
    lat: 35.1609,
    lng: 126.8946,
    address: '광주광역시 북구 하서로 52',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-15',
    source: 'official',
  },
  {
    id: 'gwangju-folk-museum',
    name: '광주시립민속박물관',
    type: 'cultural',
    lat: 35.1580,
    lng: 126.8948,
    address: '광주광역시 북구 서하로 48',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 8, ramp: true },
      wheelchair: { accessible: 'limited', note: '1층 전시 위주 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-20',
    source: 'user',
  },
  {
    id: 'gwangju-children-museum',
    name: '국립광주과학관',
    type: 'cultural',
    lat: 35.1619,
    lng: 126.8912,
    address: '광주광역시 북구 첨단과기로 235',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'gwangju-cinema-complex',
    name: 'CGV 광주터미널',
    type: 'cultural',
    lat: 35.1468,
    lng: 126.9250,
    address: '광주광역시 서구 무진대로 533',
    accessibility: {
      elevator: { available: true, floors: '1F~6F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-25',
    source: 'user',
  },
  {
    id: 'gwangju-city-hall',
    name: '광주광역시청',
    type: 'building',
    lat: 35.1604,
    lng: 126.8516,
    address: '광주광역시 서구 내방로 111',
    accessibility: {
      elevator: { available: true, floors: 'B1~12F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-30',
    source: 'official',
  },
  {
    id: 'gwangju-police-agency',
    name: '광주지방경찰청',
    type: 'building',
    lat: 35.1649,
    lng: 126.8942,
    address: '광주광역시 북구 경양로 245',
    accessibility: {
      elevator: { available: true, floors: '1F~5F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-10',
    source: 'official',
  },
  {
    id: 'gwangju-social-welfare-center',
    name: '광주장애인종합복지관',
    type: 'building',
    lat: 35.1352,
    lng: 126.9003,
    address: '광주광역시 남구 봉선로 56',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-05',
    source: 'official',
  },
  {
    id: 'gwangju-library-central',
    name: '광주광역시립도서관',
    type: 'cultural',
    lat: 35.1542,
    lng: 126.9162,
    address: '광주광역시 서구 독립로 106',
    accessibility: {
      elevator: { available: true, floors: '1F~5F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-12',
    source: 'official',
  },
  {
    id: 'gwangju-subway-1-sangmu',
    name: '상무역(광주 지하철)',
    type: 'subway',
    lat: 35.1538,
    lng: 126.8506,
    address: '광주광역시 서구 상무대로 956',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-30',
    source: 'official',
  },
  {
    id: 'gwangju-subway-1-geumnamno4',
    name: '금남로4가역(광주 지하철)',
    type: 'subway',
    lat: 35.1483,
    lng: 126.9136,
    address: '광주광역시 동구 금남로 4가',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },
  {
    id: 'gwangju-subway-1-cultural',
    name: '문화전당역(광주 지하철)',
    type: 'subway',
    lat: 35.1487,
    lng: 126.9185,
    address: '광주광역시 동구 문화전당로 38',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-10',
    source: 'official',
  },
  {
    id: 'gwangju-subway-2-bongseon',
    name: '봉선역(광주 지하철 2호선)',
    type: 'subway',
    lat: 35.1222,
    lng: 126.9130,
    address: '광주광역시 남구 봉선로 지하',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'gwangju-national-univ-education',
    name: '광주교육대학교',
    type: 'building',
    lat: 35.1503,
    lng: 126.9018,
    address: '광주광역시 북구 필문대로 55',
    accessibility: {
      elevator: { available: true, floors: '1F~6F', note: '주요 강의동 엘리베이터 설치' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: true },
      wheelchair: { accessible: 'limited', note: '신관 접근 용이, 구관 어려움' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-25',
    source: 'user',
  },
  {
    id: 'gwangju-yangnim-history',
    name: '양림동 역사문화마을',
    type: 'cultural',
    lat: 35.1385,
    lng: 126.9050,
    address: '광주광역시 남구 양림로 21',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: false, note: '골목길 비탈 다수' },
      wheelchair: { accessible: 'limited', note: '메인 도로 평탄, 골목 접근 어려움' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-05',
    source: 'user',
  },
  {
    id: 'gwangju-hangang-park',
    name: '광주 극락강 수변공원',
    type: 'public',
    lat: 35.1484,
    lng: 126.8328,
    address: '광주광역시 광산구 극락강변로',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '산책로 평탄 정비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-18',
    source: 'user',
  },
  {
    id: 'gwangju-sports-complex',
    name: '광주월드컵경기장',
    type: 'public',
    lat: 35.1648,
    lng: 126.8359,
    address: '광주광역시 서구 금화로 240',
    accessibility: {
      elevator: { available: true, floors: '1F~5F', note: '주 게이트별 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '전용 관람 구역 운영' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-08',
    source: 'official',
  },
  {
    id: 'gwangju-kimdaejung-convention',
    name: '김대중컨벤션센터',
    type: 'building',
    lat: 35.1576,
    lng: 126.8497,
    address: '광주광역시 서구 마재로 30',
    accessibility: {
      elevator: { available: true, floors: 'B1~5F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'gwangju-post-office',
    name: '광주중앙우체국',
    type: 'building',
    lat: 35.1480,
    lng: 126.9165,
    address: '광주광역시 동구 금남로 154',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: false, accessible: false },
    },
    lastUpdated: '2024-07-15',
    source: 'user',
  },

  {
    id: 'naju-station',
    name: '나주역(KTX)',
    type: 'subway',
    lat: 35.0160,
    lng: 126.7150,
    address: '전남 나주시 빛가람로 599',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'naju-national-museum',
    name: '국립나주박물관',
    type: 'cultural',
    lat: 35.0098,
    lng: 126.7282,
    address: '전남 나주시 반남면 신촌리 407-1',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-20',
    source: 'official',
  },
  {
    id: 'naju-city-hall',
    name: '나주시청',
    type: 'building',
    lat: 35.0158,
    lng: 126.7103,
    address: '전남 나주시 빛가람로 730',
    accessibility: {
      elevator: { available: true, floors: 'B1~7F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-30',
    source: 'official',
  },
  {
    id: 'naju-pear-museum',
    name: '나주배박물관',
    type: 'cultural',
    lat: 35.0369,
    lng: 126.7120,
    address: '전남 나주시 배단지길 14',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'limited' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-08',
    source: 'user',
  },

  {
    id: 'damyang-bamboo-forest',
    name: '담양 죽녹원',
    type: 'cultural',
    lat: 35.3222,
    lng: 126.9902,
    address: '전남 담양군 담양읍 죽녹원로 119',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: false, note: '산책로 오르막 구간 다수' },
      wheelchair: { accessible: 'limited', note: '하단부 평탄 구간만 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-05',
    source: 'user',
  },
  {
    id: 'damyang-metasequoia-road',
    name: '담양 메타세쿼이아 가로수길',
    type: 'public',
    lat: 35.3381,
    lng: 126.9820,
    address: '전남 담양군 담양읍 메타세쿼이아로 12',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '평탄한 직선 산책로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-20',
    source: 'user',
  },
  {
    id: 'damyang-city-hall',
    name: '담양군청',
    type: 'building',
    lat: 35.3219,
    lng: 126.9879,
    address: '전남 담양군 담양읍 추성로 1371',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-22',
    source: 'official',
  },

  {
    id: 'hwasun-dolmen',
    name: '화순 고인돌유적지',
    type: 'cultural',
    lat: 35.0640,
    lng: 126.9820,
    address: '전남 화순군 도곡면 효산리 763',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '탐방로 평탄 정비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-30',
    source: 'official',
  },
  {
    id: 'hwasun-city-hall',
    name: '화순군청',
    type: 'building',
    lat: 35.0648,
    lng: 126.9867,
    address: '전남 화순군 화순읍 수만로 394',
    accessibility: {
      elevator: { available: true, floors: '1F~4F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-05',
    source: 'official',
  },
  {
    id: 'hwasun-hospital',
    name: '화순전남대학교병원',
    type: 'hospital',
    lat: 35.0620,
    lng: 126.9808,
    address: '전남 화순군 화순읍 서양로 322',
    accessibility: {
      elevator: { available: true, floors: 'B3~12F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-25',
    source: 'official',
  },

  {
    id: 'hampyeong-butterfly',
    name: '함평나비대축제장',
    type: 'public',
    lat: 35.0643,
    lng: 126.5169,
    address: '전남 함평군 함평읍 영산로 1168',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-06-15',
    source: 'user',
  },
  {
    id: 'yeongwang-nuclear-museum',
    name: '영광 원자력홍보관',
    type: 'cultural',
    lat: 35.4388,
    lng: 126.5020,
    address: '전남 영광군 홍농읍 계마항길 46-41',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-08',
    source: 'official',
  },

  {
    id: 'jangseong-red-maple-forest',
    name: '장성 백양사',
    type: 'cultural',
    lat: 35.4568,
    lng: 126.8820,
    address: '전남 장성군 북하면 백양로 1239',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 15, ramp: false, note: '산사 진입로 비탈, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '주차장~매표소 구간만 접근 가능' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-07-18',
    source: 'user',
  },

  {
    id: 'gwangju-hanyang-hospital',
    name: '광주한양병원',
    type: 'hospital',
    lat: 35.1408,
    lng: 126.8600,
    address: '광주광역시 서구 상무대로 904',
    accessibility: {
      elevator: { available: true, floors: 'B1~8F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-05',
    source: 'user',
  },
  {
    id: 'gwangju-sangmu-park',
    name: '상무시민공원',
    type: 'public',
    lat: 35.1558,
    lng: 126.8495,
    address: '광주광역시 서구 상무평화로 30',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 전체 평탄한 산책로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-25',
    source: 'user',
  },
  {
    id: 'gwangju-arts-street',
    name: '광주 예술의거리',
    type: 'cultural',
    lat: 35.1476,
    lng: 126.9180,
    address: '광주광역시 동구 충장로5가',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '보행자 전용구역 평탄 정비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-12',
    source: 'user',
  },
  {
    id: 'gwangju-cheomdan-welfare',
    name: '광주 첨단복지관',
    type: 'building',
    lat: 35.1882,
    lng: 126.8530,
    address: '광주광역시 북구 첨단연신로 72',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-01',
    source: 'official',
  },
  {
    id: 'gwangju-national-disability-sports',
    name: '광주장애인체육관',
    type: 'public',
    lat: 35.1560,
    lng: 126.8960,
    address: '광주광역시 북구 경양로 174',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-28',
    source: 'official',
  },

  {
    id: 'daejeon-station',
    name: '대전역',
    type: 'subway',
    lat: 36.3322,
    lng: 127.4345,
    address: '대전광역시 동구 중앙로 215',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-15',
    source: 'official',
  },
  {
    id: 'expo-science-park',
    name: '엑스포과학공원',
    type: 'public',
    lat: 36.3742,
    lng: 127.3850,
    address: '대전광역시 유성구 대덕대로 480',
    accessibility: {
      elevator: { available: true, floors: '1F~3F', note: '주요 전시관 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-25',
    source: 'user',
  },

  {
    id: 'hwaseong-fortress',
    name: '수원화성',
    type: 'cultural',
    lat: 37.2851,
    lng: 127.0139,
    address: '경기도 수원시 팔달구 행궁로 11',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false, note: '입장권 발매기 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '성벽 순환로 계단 다수, 우회 평지 경로 있음' },
      wheelchair: { accessible: 'limited', note: '행궁 내부 일부 구역 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-10',
    source: 'user',
  },
  {
    id: 'suwon-station',
    name: '수원역',
    type: 'subway',
    lat: 37.2655,
    lng: 127.0005,
    address: '경기도 수원시 팔달구 매산로1가 1',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-30',
    source: 'official',
  },

  {
    id: 'jeonju-hanok-village',
    name: '전주한옥마을',
    type: 'cultural',
    lat: 35.8146,
    lng: 127.1467,
    address: '전북 전주시 완산구 기린대로 99',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 10, ramp: false, note: '골목 비탈 다수, 일부 완만한 우회 경로 있음' },
      wheelchair: { accessible: 'limited', note: '메인 거리는 평지, 좁은 골목 접근 어려움' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-01',
    source: 'user',
  },
  {
    id: 'jeonju-national-museum',
    name: '국립전주박물관',
    type: 'cultural',
    lat: 35.8238,
    lng: 127.1100,
    address: '전북 전주시 완산구 쑥고개로 249',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-18',
    source: 'official',
  },

  {
    id: 'gyeongju-national-museum',
    name: '국립경주박물관',
    type: 'cultural',
    lat: 35.8341,
    lng: 129.2243,
    address: '경북 경주시 일정로 186',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-20',
    source: 'official',
  },
  {
    id: 'bulguksa',
    name: '불국사',
    type: 'cultural',
    lat: 35.7898,
    lng: 129.3316,
    address: '경북 경주시 불국로 385',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 30, ramp: false, note: '청운교·백운교 등 가파른 계단 다수, 우회 경사로 있음' },
      wheelchair: { accessible: 'limited', note: '일부 평지 경내 접근 가능, 사전 문의 필요' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-25',
    source: 'user',
  },

  {
    id: 'jeju-airport',
    name: '제주국제공항',
    type: 'building',
    lat: 33.5113,
    lng: 126.4928,
    address: '제주특별자치도 제주시 공항로 2',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes', note: '무료 휠체어 대여 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'jeju-national-museum',
    name: '국립제주박물관',
    type: 'cultural',
    lat: 33.5135,
    lng: 126.5300,
    address: '제주특별자치도 제주시 일주동로 17',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-12',
    source: 'official',
  },
  {
    id: 'jeju-teddy-bear-museum',
    name: '제주테디베어뮤지엄',
    type: 'cultural',
    lat: 33.2451,
    lng: 126.4124,
    address: '제주특별자치도 서귀포시 중문관광로 110번길 31',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-08',
    source: 'user',
  },

  {
    id: 'gangneung-station',
    name: '강릉역',
    type: 'subway',
    lat: 37.7878,
    lng: 128.9387,
    address: '강원특별자치도 강릉시 경강로 2048',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-18',
    source: 'official',
  },
  {
    id: 'gyeongpodae',
    name: '경포대',
    type: 'public',
    lat: 37.8071,
    lng: 128.9000,
    address: '강원특별자치도 강릉시 경포로 365',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '전망대 계단, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '호수 주변 산책로는 접근 가능' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-06-05',
    source: 'user',
  },

  {
    id: 'changwon-station',
    name: '창원중앙역',
    type: 'subway',
    lat: 35.2539,
    lng: 128.6642,
    address: '경남 창원시 의창구 중앙대로 252',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-22',
    source: 'official',
  },

  {
    id: 'chuncheon-station',
    name: '춘천역',
    type: 'subway',
    lat: 37.8663,
    lng: 127.7326,
    address: '강원특별자치도 춘천시 동내면 외솔길 109',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 1F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-12',
    source: 'osm',
  },

  {
    id: 'ulsan-station',
    name: '울산역(KTX)',
    type: 'subway',
    lat: 35.5556,
    lng: 129.1802,
    address: '울산광역시 울주군 삼남읍 울산역로 125',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-30',
    source: 'official',
  },
  {
    id: 'ulsan-museum',
    name: '울산박물관',
    type: 'cultural',
    lat: 35.5380,
    lng: 129.3119,
    address: '울산광역시 남구 두왕로 277',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-08',
    source: 'user',
  },

  {
    id: 'pangyo-station',
    name: '판교역',
    type: 'subway',
    lat: 37.3943,
    lng: 127.1111,
    address: '경기도 성남시 분당구 판교역로 160',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-08',
    source: 'official',
  },

  {
    id: 'ilsan-western-lake',
    name: '일산 호수공원',
    type: 'public',
    lat: 37.6757,
    lng: 126.7717,
    address: '경기도 고양시 일산동구 호수로 595',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: false, ramp: true, note: '공원 전체 평탄한 보행로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-22',
    source: 'user',
  },

  {
    id: 'cheongju-station',
    name: '오송역',
    type: 'subway',
    lat: 36.6227,
    lng: 127.3128,
    address: '충북 청주시 흥덕구 오송읍 오송가락로 123',
    accessibility: {
      elevator: { available: true, floors: 'B1~지상 2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'official',
  },
  {
    id: 'cheongju-national-museum',
    name: '국립청주박물관',
    type: 'cultural',
    lat: 36.6433,
    lng: 127.4910,
    address: '충북 청주시 상당구 명암로 143',
    accessibility: {
      elevator: { available: true, floors: '1F~2F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-03',
    source: 'official',
  },

  {
    id: 'mokpo-national-maritime',
    name: '국립해양문화재연구소',
    type: 'cultural',
    lat: 34.7933,
    lng: 126.3811,
    address: '전남 목포시 남농로 136',
    accessibility: {
      elevator: { available: true, floors: '1F~3F' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-06-28',
    source: 'user',
  },

  {
    id: 'hahoe-village',
    name: '안동하회마을',
    type: 'cultural',
    lat: 36.5393,
    lng: 128.5196,
    address: '경북 안동시 풍천면 전서로 186',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 5, ramp: false, note: '마을 내 비포장·비탈길 다수' },
      wheelchair: { accessible: 'limited', note: '메인 진입로 평탄, 마을 내부 일부 어려움' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-18',
    source: 'user',
  },




];
