import { AccessibilityLocation } from './types';

export const sampleLocations: AccessibilityLocation[] = [
  {
    id: 'seoul-station',
    name: '서울역',
    type: 'subway',
    lat: 37.5547,
    lng: 126.9707,
    address: '서울특별시 용산구 한강대로 405',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F', note: '1·4호선, KTX 모든 층 연결' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '승차권 발매기 음성 안내 지원' },
      steps: { hasSteps: false, ramp: true, note: '주 출입구 경사로 완비' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-10',
    source: 'official',
  },
  {
    id: 'gangnam-station',
    name: '강남역',
    type: 'subway',
    lat: 37.4979,
    lng: 127.0276,
    address: '서울특별시 강남구 강남대로 396',
    accessibility: {
      elevator: { available: true, floors: 'B6~지상 1F', note: '2호선 상·하행 모두 엘리베이터 이용 가능' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: false, note: '일부 발매기만 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-22',
    source: 'official',
  },
  {
    id: 'hongik-station',
    name: '홍대입구역',
    type: 'subway',
    lat: 37.5572,
    lng: 126.9245,
    address: '서울특별시 마포구 양화로 160',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 2F' },
      kiosk: { available: true, voiceSupport: false, note: '음성 안내 미지원, 터치스크린만 가능' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-15',
    source: 'user',
  },
  {
    id: 'gwanghwamun-square',
    name: '광화문광장',
    type: 'public',
    lat: 37.5752,
    lng: 126.9769,
    address: '서울특별시 종로구 세종대로 172',
    accessibility: {
      elevator: { available: false, note: '지하 공간 없음' },
      kiosk: { available: true, voiceSupport: false, note: '안내 키오스크 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 3, ramp: true, note: '광장 진입 단차 3cm 이하, 경사로 있음' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-08-30',
    source: 'user',
  },
  {
    id: 'severance-hospital',
    name: '세브란스병원',
    type: 'hospital',
    lat: 37.5622,
    lng: 126.9405,
    address: '서울특별시 서대문구 연세로 50-1',
    accessibility: {
      elevator: { available: true, floors: 'B5~지상 21F', note: '본관·별관 모든 층 엘리베이터 운행' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '원무 접수 키오스크 음성·대형글씨 완비' },
      steps: { hasSteps: false, ramp: true, note: '주출입구 자동문·경사로' },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-01',
    source: 'official',
  },
  {
    id: 'coex-mall',
    name: 'COEX 몰',
    type: 'shopping',
    lat: 37.5113,
    lng: 127.0592,
    address: '서울특별시 강남구 영동대로 513',
    accessibility: {
      elevator: { available: true, floors: 'B3~5F' },
      kiosk: { available: true, voiceSupport: false, note: '안내 키오스크 음성 미지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-05',
    source: 'user',
  },
  {
    id: 'gyeongbokgung',
    name: '경복궁',
    type: 'cultural',
    lat: 37.5796,
    lng: 126.9770,
    address: '서울특별시 종로구 사직로 161',
    accessibility: {
      elevator: { available: false },
      kiosk: { available: true, voiceSupport: false, note: '입장권 발매 키오스크, 음성 미지원' },
      steps: { hasSteps: true, maxHeightCm: 15, ramp: false, note: '정문(흥례문) 계단 단차 약 15cm, 경사로 없음' },
      wheelchair: { accessible: 'limited', note: '일부 구역만 접근 가능, 사전 문의 권장' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-07-20',
    source: 'user',
  },
  {
    id: 'itaewon-station',
    name: '이태원역',
    type: 'subway',
    lat: 37.5345,
    lng: 126.9943,
    address: '서울특별시 용산구 이태원로 177',
    accessibility: {
      elevator: { available: true, floors: 'B2~지상 1F' },
      kiosk: { available: true, voiceSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-09-01',
    source: 'osm',
  },
  {
    id: 'lotte-world-tower',
    name: '롯데월드타워',
    type: 'building',
    lat: 37.5126,
    lng: 127.1026,
    address: '서울특별시 송파구 올림픽로 300',
    accessibility: {
      elevator: { available: true, floors: 'B7~123F', note: '고속 엘리베이터 및 장애인용 별도 엘리베이터 운영' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-11-15',
    source: 'official',
  },
  {
    id: 'insadong',
    name: '인사동 쌈지길',
    type: 'shopping',
    lat: 37.5742,
    lng: 126.9855,
    address: '서울특별시 종로구 인사동길 44',
    accessibility: {
      elevator: { available: true, floors: 'B1~4F', note: '나선형 통로 외 엘리베이터 별도 운영' },
      kiosk: { available: false, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 8, ramp: true, note: '일부 샵 입구 단차 최대 8cm' },
      wheelchair: { accessible: 'limited', note: '엘리베이터 이용 시 대부분 층 접근 가능' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-06-10',
    source: 'user',
  },
  {
    id: 'national-museum',
    name: '국립중앙박물관',
    type: 'cultural',
    lat: 37.5240,
    lng: 126.9799,
    address: '서울특별시 용산구 서빙고로 137',
    accessibility: {
      elevator: { available: true, floors: 'B1~3F' },
      kiosk: { available: true, voiceSupport: true, largeFontSupport: true, note: '안내·티켓 키오스크 완전 음성 지원' },
      steps: { hasSteps: false, ramp: true },
      wheelchair: { accessible: 'yes' },
      toilet: { available: true, accessible: true },
    },
    lastUpdated: '2024-10-18',
    source: 'official',
  },
  {
    id: 'sinchon-station',
    name: '신촌역',
    type: 'subway',
    lat: 37.5551,
    lng: 126.9368,
    address: '서울특별시 서대문구 신촌로 83',
    accessibility: {
      elevator: { available: false, note: '엘리베이터 미설치, 에스컬레이터만 운영' },
      kiosk: { available: true, voiceSupport: false },
      steps: { hasSteps: true, maxHeightCm: 20, ramp: false, note: '출구 계단 단차 약 20cm, 경사로 없음' },
      wheelchair: { accessible: 'no', note: '휠체어 이용 매우 어려움, 인근 홍대입구역 이용 권장' },
      toilet: { available: true, accessible: false },
    },
    lastUpdated: '2024-08-05',
    source: 'user',
  },
];
